---
project: {name}
default-region: {region}
code-bucket: {bucket}
apps:
  - gordon.contrib.lambdas
  - octoturtle

apigateway:
  {name}:
    description: An API for receiving GitHub webhooks.
    resources:
      /:
        methods: [POST]
        integration:
          lambda: octoturtle.octoturtle-handler
